### ISSUE TITLE
Forwarding ssh-agent

### ISSUE THREAD

**Issue by tscolari** [mislav/git-deploy#55]
Is it possible to forward the ssh agent on the git push?

I tried adding `:forward_agent => true` in the `Net::SSH.start` call, but it doesn't seem to affect the `git push`. I'm having access denied when the submodules update get run.

**Comment by sesam** [comment]
Suggest close: Already answered. Further questions on this topic, please ask in a support forum. Maybe one linked here: https://stackexchange.com/sites

**Comment by mislav** [comment]
True. I recommend going the `~/.ssh/config` route by adding `ForwardAgent yes` directive to the host of your choice.
