### ISSUE TITLE
delpoy without commit

### ISSUE THREAD

**Issue by TangMonk** [mislav/git-deploy#76]
thanks for your work. 

I wanna to know how to git push delpoy without commit,  simmlar  rsync

**Comment by mislav** [comment]
There is no easy way to trigger a deploy without a commit, unfortunately. You would have to SSH into your instance and run the post-push script in your projects manually.

There is a trick you could do, however. You can force-push an older commit, such as the previous commit. Then you can push the latest state of the branch back in. You don't need to create extra commits for this, and it will trigger a deploy:

```
$ git push production HEAD^:master
$ git push production master
```
